name: check-skip-staging

on:
  pull_request:
    branches: 
      - master

jobs:
  check-skip-staging:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: gusaul/check-skip-staging@1.0.0
